version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blaBla
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

  server:
    build:
      context: ./server
    container_name: my-node-server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: blaBla
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - shared-network

  client:
    build:
      context: ./client
    container_name: my-react-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    external: true
